services:
  mindlines:
    build: .
    ports:
      - 127.0.0.1:8070:8080
      - 127.0.0.1:3001:3000
    volumes:
      - ./mindlines-backend/content:/app/content
    environment:
      NUXT_PUBLIC_BACKEND_URL: http://localhost:8070
      FRONTEND_URL: http://localhost:3001
